forge 'https://forge.puppet.com'

# Modules from the Puppet Forge
# Versions should be updated to be the latest at the time you start
mod 'puppetlabs/stdlib',      '4.25.1'
mod 'hardening-os_hardening', '2.4.0'
mod 'puppet-augeasproviders_sysctl', '3.2.0'